In [1]:
import numpy as np
import tensorflow as tf


In [17]:
aa = tf.constant([[[1,1,1]],[[1,1,3]]])
print(tf.rank(aa))
print(aa)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(
[[[1 1 1]]

 [[1 1 3]]], shape=(2, 1, 3), dtype=int32)


In [18]:
b = tf.constant(['Hello'])
print(tf.rank(b))
print(b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([b'Hello'], shape=(1,), dtype=string)


# 난수생성

In [22]:
rand = tf.random.uniform([1],0,1) # def random_uniform(shape, 최솟값=0, 최댓값=None, dtype=dtypes.float32, seed=None, name=None)
print(rand.shape)
print(rand)

(1,)
tf.Tensor([0.26496744], shape=(1,), dtype=float32)


In [24]:
rand2= tf.random.normal([1,2],0,1) # def random_normal(shape, mean=0.0, stddev=1.0, dtype=dtypes.float32, seed=None, name=None)
print(rand2.shape)
print(rand2)

(1, 2)
tf.Tensor([[-1.8390859 -0.3259227]], shape=(1, 2), dtype=float32)


# 즉시 실행 모드 (Eager Mode) 지원


*  즉시 실행모드를 통해 텐서플로우를 파이썬처럼 사용할 수 있음
*  1.x 버전에서는 '그래프'를 생성하고, 초기화 한 뒤에 세션을 통해 값을 흐리게 하는 작업을 진행해야 함.



In [25]:
a = tf.constant(3)
b = tf.constant(2)

In [26]:
print(tf.add(a,b))
print(a+b)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [28]:
print(tf.subtract(a,b))
print(a-b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [30]:
print(tf.multiply(a,b))
print(a*b)

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


# 텐서플로우 <-> 넘파이

*   numpy()
*   tf.convet_to_tensor()




In [31]:
c = tf.add(a,b).numpy()
print(type(c))

<class 'numpy.int32'>


In [32]:
c_square = np.square(c,dtype=np.float32)
c_tensor = tf.convert_to_tensor